#!/bin/bash
# Complete Password Reset Setup Script

echo "🎉 Password Reset System - Complete Setup"
echo "=========================================="
echo ""

cd ~/src/renterinsight_api

echo "📦 Step 1: Running Migrations..."
bundle exec rails db:migrate
if [ $? -ne 0 ]; then
    echo "❌ Migration failed!"
    exit 1
fi
echo "✅ Migrations complete!"
echo ""

echo "👥 Step 2: Creating Test Users..."
bundle exec rails runner create_test_users_password_reset.rb
if [ $? -ne 0 ]; then
    echo "❌ User creation failed!"
    exit 1
fi
echo ""

echo "⚙️  Step 3: Settings Configuration"
echo "=========================================="
echo ""
echo "📧 EMAIL CONFIGURATION (Optional - for real delivery)"
echo "To send real emails, configure SMTP in Rails console:"
echo ""
echo "bin/rails console"
echo ""
echo "Setting.set('Platform', 0, 'communications', {"
echo "  email: {"
echo "    provider: 'smtp',"
echo "    fromEmail: 't+admin@renterinsight.com',"
echo "    fromName: 'RenterInsight',"
echo "    smtpHost: 'smtp.gmail.com',"
echo "    smtpPort: 587,"
echo "    smtpUsername: 't+admin@renterinsight.com',"
echo "    smtpPassword: 'your_gmail_app_password',"
echo "    isEnabled: true"
echo "  }"
echo "})"
echo ""
echo "📱 SMS CONFIGURATION (Optional - for real delivery)"
echo "To send real SMS, add Twilio settings:"
echo ""
echo "Setting.set('Platform', 0, 'communications', {"
echo "  sms: {"
echo "    provider: 'twilio',"
echo "    fromNumber: '+13035709810',"
echo "    twilioAccountSid: 'your_twilio_sid',"
echo "    twilioAuthToken: 'your_twilio_token',"
echo "    isEnabled: true"
echo "  }"
echo "})"
echo ""
echo "=========================================="
echo ""
echo "✅ SETUP COMPLETE!"
echo ""
echo "🧪 TEST THE SYSTEM:"
echo "=========================================="
echo ""
echo "1️⃣  Test Admin Email Reset:"
echo "curl -X POST http://localhost:3001/api/auth/request_password_reset \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"email\": \"t+admin@renterinsight.com\","
echo "    \"delivery_method\": \"email\","
echo "    \"user_type\": \"admin\""
echo "  }'"
echo ""
echo "2️⃣  Test Client Email Reset:"
echo "curl -X POST http://localhost:3001/api/auth/request_password_reset \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"email\": \"t+client@renterinsight.com\","
echo "    \"delivery_method\": \"email\","
echo "    \"user_type\": \"client\""
echo "  }'"
echo ""
echo "3️⃣  Test Admin SMS Reset (Phone):"
echo "curl -X POST http://localhost:3001/api/auth/request_password_reset \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"phone\": \"+13035709810\","
echo "    \"delivery_method\": \"sms\","
echo "    \"user_type\": \"admin\""
echo "  }'"
echo ""
echo "4️⃣  Test Client SMS Reset (Phone):"
echo "curl -X POST http://localhost:3001/api/auth/request_password_reset \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"phone\": \"+13035709810\","
echo "    \"delivery_method\": \"sms\","
echo "    \"user_type\": \"client\""
echo "  }'"
echo ""
echo "=========================================="
echo "🎉 Ready to test password reset!"
