# frozen_string_literal: true

class CommunicationMailer < ApplicationMailer
  def send_communication(to:, subject:, body:, from_email:, from_name:, cc: nil, bcc: nil, reply_to: nil, file_attachments: [], inline_images: [])
    # Add file attachments if present (BEFORE calling mail)
    # Renamed parameter from 'attachments' to 'file_attachments' to avoid shadowing the mail attachments method

    Rails.logger.info "[CommunicationMailer] Processing #{file_attachments&.length || 0} attachments"
    Rails.logger.info "[CommunicationMailer] Reply-To: #{reply_to}" if reply_to.present?

    if file_attachments.present?
      file_attachments.each_with_index do |file_attachment, index|
        next unless file_attachment.present?

        begin
          if file_attachment.respond_to?(:original_filename) && file_attachment.respond_to?(:read)
            # ActionDispatch::Http::UploadedFile
            filename = file_attachment.original_filename
            file_content = file_attachment.read
            Rails.logger.info "[CommunicationMailer] Attaching file #{index + 1}: #{filename} (#{file_content.bytesize} bytes)"
            attachments[filename] = file_content
          elsif file_attachment.respond_to?(:path) && file_attachment.respond_to?(:read)
            # File object
            filename = File.basename(file_attachment.path)
            file_content = file_attachment.read
            Rails.logger.info "[CommunicationMailer] Attaching file #{index + 1}: #{filename} (#{file_content.bytesize} bytes)"
            attachments[filename] = file_content
          elsif file_attachment.is_a?(Hash)
            # Hash with filename and content
            if file_attachment[:filename] && file_attachment[:content]
              Rails.logger.info "[CommunicationMailer] Attaching file #{index + 1}: #{file_attachment[:filename]}"
              attachments[file_attachment[:filename]] = file_attachment[:content]
            end
          end
        rescue => e
          Rails.logger.error "[CommunicationMailer] Failed to attach file #{index + 1}: #{e.message}"
          Rails.logger.error e.backtrace.first(3).join("\n")
        end
      end
    end

    # Attach inline images (CID-referenced) and rewrite the rendered body so the
    # <img src="..."> URLs point at cid:... instead of the original web URL.
    # This is what makes the image render in Outlook (which blocks remote images).
    rewritten_body = body
    if inline_images.present?
      Rails.logger.info "[CommunicationMailer] Processing #{inline_images.length} inline images"
      inline_images.each_with_index do |image, index|
        next unless image.is_a?(Hash) && image[:filename].present? && image[:content].present?

        begin
          filename = image[:filename]
          attachments.inline[filename] = image[:content]
          cid_url = attachments[filename].url  # "cid:<auto-generated@hostname>"
          Rails.logger.info "[CommunicationMailer] Inline image #{index + 1}: #{filename} (#{image[:content].bytesize} bytes) -> #{cid_url}"

          if image[:replace_url].present? && rewritten_body.is_a?(String)
            rewritten_body = rewritten_body.gsub(image[:replace_url], cid_url)
          end
        rescue => e
          Rails.logger.error "[CommunicationMailer] Failed to attach inline image #{index + 1}: #{e.message}"
        end
      end
    end

    # Build mail options
    mail_options = {
      to: to,
      from: "#{from_name} <#{from_email}>",
      cc: cc,
      bcc: bcc,
      subject: subject
    }

    # Add reply_to if provided
    mail_options[:reply_to] = reply_to if reply_to.present?

    # Now create and send the mail
    mail(mail_options) do |format|
      if rewritten_body&.include?('<html') || rewritten_body&.include?('<body') || rewritten_body&.include?('<div') || rewritten_body&.include?('<table') || rewritten_body&.include?('<p ')
        format.html { render html: rewritten_body.html_safe }
        format.text { render plain: ActionController::Base.helpers.strip_tags(rewritten_body) }
      else
        format.text { render plain: rewritten_body }
      end
    end
  end
end
