# frozen_string_literal: true

# Something a visitor did inside a session on a landing page.
class PageVisitEvent < ApplicationRecord
  belongs_to :page_visit

  # Scroll depth is recorded at milestones rather than continuously — a
  # scroll listener that writes on every frame would generate thousands of
  # rows per visit and tell you nothing more than four of them do.
  SCROLL_EVENTS = %w[scroll_25 scroll_50 scroll_75 scroll_100].freeze

  # Video quartiles are the reason the video block is worth having on a landing
  # page: a page where most visitors reach 75% is working even before anyone
  # submits a form.
  # video_unmute is the intent signal on an autoplaying clip, which browsers
  # only ever start muted. A play there is generated by every visitor and says
  # nothing; someone reaching for the speaker is asking to hear it, and on a
  # video with no narration that answers whether recording some is worthwhile.
  VIDEO_EVENTS = %w[video_play video_25 video_50 video_75 video_complete video_unmute].freeze

  # form_start fires on first focus, which is what makes abandonment
  # measurable — a page with many starts and few submits has a form problem,
  # not a traffic problem.
  ENGAGEMENT_EVENTS = %w[view cta_click outbound_click form_start form_submit].freeze

  # What a visitor did with a specific home, carried in payload['vehicle_id'].
  #
  # These ride on PageVisitEvent rather than a table of their own because the
  # question worth answering is not "how many views did this home get" but "which
  # homes did the people who became leads look at". That only works if the home
  # is attached to the same session that carries the source, the identity and the
  # conversion, which is exactly what a visit already is.
  #
  # home_view is a card impression in the grid, home_detail is opening the home,
  # home_inquiry is asking about it. The three separate because interest is a
  # funnel: a home with many impressions and no detail views has a photo or a
  # price problem, one with many detail views and no inquiries has a different
  # problem, and a single counter cannot tell them apart.
  INVENTORY_EVENTS = %w[home_view home_detail home_inquiry].freeze

  EVENT_TYPES = (SCROLL_EVENTS + VIDEO_EVENTS + ENGAGEMENT_EVENTS + INVENTORY_EVENTS).freeze

  validates :event_type, inclusion: { in: EVENT_TYPES }
  validates :occurred_at, presence: true

  scope :of_type, ->(type) { where(event_type: type) }
  scope :video, -> { where(event_type: VIDEO_EVENTS) }
  scope :scroll, -> { where(event_type: SCROLL_EVENTS) }
  scope :inventory, -> { where(event_type: INVENTORY_EVENTS) }

  # The home this event was about. Nil for every non-inventory event, which is
  # why callers filter with .inventory first.
  def vehicle_id
    payload.is_a?(Hash) ? payload['vehicle_id'].presence&.to_i : nil
  end
end
