# frozen_string_literal: true

# Expires auto-generated social drafts nobody acted on.
#
# Deliberately narrow — it only ever touches rows that are all of:
#   * status 'draft'          (never approved/scheduled/published/failed)
#   * generated by a schedule (generation_context carries its schedule_id)
#   * older than that schedule's draft_retention_days
#
# A draft a human saved by hand has no schedule_id and is never touched. The
# expiry is a soft delete so a mis-expired post can be brought back, and so
# lead/deal attribution already recorded against the row survives.
class PurgeStaleSocialDraftsJob < ApplicationJob
  queue_as :default

  def perform
    expired = 0

    SocialPostSchedule.where(is_deleted: [false, nil]).find_each do |schedule|
      days = schedule.draft_retention_days.to_i
      next if days <= 0 # 0 disables expiry for this schedule

      stale = stale_drafts_for(schedule, days)
      next if stale.empty?

      ids = stale.map(&:id)
      SocialPost.where(id: ids).update_all(is_deleted: true, updated_at: Time.current)
      expired += ids.length

      Rails.logger.info(
        "[PurgeStaleSocialDraftsJob] schedule=#{schedule.id} retention=#{days}d " \
        "expired=#{ids.length} ids=#{ids.join(',')}"
      )
    end

    Rails.logger.info "[PurgeStaleSocialDraftsJob] expired=#{expired}"
    expired
  end

  private

  # generation_context is jsonb, but schedule_id is written as an integer while
  # older rows may hold it as a string — compare as text so both match.
  def stale_drafts_for(schedule, days)
    SocialPost
      .where(company_id: schedule.company_id, status: 'draft')
      .where(is_deleted: [false, nil])
      .where('social_posts.created_at < ?', days.days.ago)
      .where("generation_context->>'schedule_id' = ?", schedule.id.to_s)
      .to_a
  end
end
